### ISSUE TITLE
lib.d.ts types are too loose: provide a "strict" version with more accurate typings?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TSJS-lib-generator#328]
Let's use `setTimeout`'s typings as an example:

```typescript
declare function setTimeout(handler: (...args: any[]) => void, timeout: number): number;
declare function setTimeout(handler: any, timeout?: any, ...args: any[]): number;
```

That's pretty forgiving. In reality, the _recommended_ usage would be:

```typescript
declare function setTimeout(handler: (...args: any[]) => void, timeout: number, ...args: any[]): number;
```

...and if & when variadic kinds are supported (https://github.com/Microsoft/TypeScript/issues/5453), that would become stricter.

Such a loose backwards-compatible `lib.d.ts` allows improper usage of native APIs. It would be useful to have a "strict" version that provides only the _recommended_ usage.

In conjunction with #327, it'd be great if a separate type could be created for these types, so we can dependency-inject them in code.

```typescript
type SetTimeout = (handler: (...args: any[]) => void, timeout: number, ...args: any[]) => number;
```

```typescript
declare const setTimeout: SetTimeout;
```

**Comment by falsandtru** [comment]
Already filed to https://github.com/Microsoft/TypeScript/issues/19635

**Comment by JoshuaKGoldberg** [comment]
@falsandtru I filed under Microsoft/Typescript and was redirected here. Funny :)

@mhegazy ?

**Comment by mhegazy** [comment]
The issue https://github.com/Microsoft/TypeScript/issues/20175 seemed like a general problem with the library, if all you need is settimeout, then you are welcome to submit a fix for it.

The redirection was not to ask you to file a bug, but to get you to look at how the library is generated, you ended up filing a new issue.

Whether the issue is on https://github.com/Microsoft/TSJS-lib-generator or https://github.com/Microsoft/TypeScript should not make much difference. if definitions do not match the standard we have means to override the definitions by adding an entry to https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/overridingTypes.json.

**Comment by JoshuaKGoldberg** [comment]
> override the definitions

Would it be considered a breaking change to modify types to be less permissive?

**Comment by mhegazy** [comment]
yes, and we do list them under breaking changes.. see https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-to-dom-apis-in-the-standard-library-1 for an example.

**Comment by falsandtru** [comment]
FYI, all of the bugs of built-in types should basically be filed to https://github.com/Microsoft/TypeScript. The bugs are managed there. See https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=label%3A%22Domain%3A%20lib.d.ts%22%20

**Comment by JoshuaKGoldberg** [comment]
SGTM!

Looking forward to having these all getting tightened up.
