### ISSUE TITLE
Typing of HTMLSelectElement

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TSJS-lib-generator#68]
There are several properties of `HTMLSelectElement` that could be typed more specifically.  For example [`options`](https://github.com/Microsoft/TypeScript/blob/0f67f4b6f1589756906782f1ac02e6931e1cff13/src/lib/dom.generated.d.ts#L6147) is typed as `HTMLCollection` when it could be typed as `HTMLOptionsCollection` (which isn't currently typed) which it's index would be of type `HTMLOptionElement`. (see: [MDN HTMLSelectElement](https://developer.mozilla.org/en/docs/Web/API/HTMLSelectElement))

I would also argue that `HTMLCollection` should actually return `HTMLElement` instead of `Element`.

Note, this "broke" some things with TS 1.8.2 because previously the index returned `any` thereby allowing a lot of code to "just compile".

**Comment by zhengbli** [comment]
If I understand correctly, you are saying:
- `HTMLSelectElement.options` should be of type `HTMLOptionsCollection` instead of `HTMLCollection`

Agreed. There was a patch before that overrides the type to `HTMLCollection`, it is `HTMLOptionsCollection` in the spec.

- The item in `HTMLOptionsCollection` should be of type `HTMLOptionsElement`, which currently it is `Element` because of inheritance from `HTMLCollection`.

Agreed.

- The item in `HTMLCollection` should be of type `HTMLElement` instead of `Element`.

According to https://dom.spec.whatwg.org/#htmlcollection:

> Elements is the better solution for representing a collection of elements. HTMLCollection is an historical artifact we cannot rid the web of. 
So I would argue historically `HTMLCollection` serves as a generic collection of all `Element`s, changing that would break a lot of code. I would rather stick to the spec on this one.

**Comment by kitsonk** [comment]
> So I would argue historically HTMLCollection serves as a generic collection of all Elements, changing that would break a lot of code. I would rather stick to the spec on this one.

You are right, the spec is quite clear it is a collection of `Element` not a collection of `HTMLElement`.

Thanks!

**Comment by FranklinWhale** [comment]
Perhaps this issue has been solved by this [commit](https://github.com/Microsoft/TSJS-lib-generator/commit/363eccd04412ce6e72097b2b3c897076fabab5b0).
